apiVersion: batch/v1
kind: Job
metadata:
  name: aggregator
spec:
  template:
    spec:
      containers:
      - name: aggregator
        image: aggregator-image:latest
        imagePullPolicy: Never
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_USER
          value: user
        - name: RABBITMQ_PASSWORD
          value: password
        volumeMounts:
        - mountPath: /output
          name: output-volume
      volumes:
      - name: output-volume
        persistentVolumeClaim:
          claimName: output-pvc
      restartPolicy: Never
  

