# base on latest python image
FROM python:latest

COPY worker.py infofile.py constants.py ./

RUN pip install pika uproot awkward matplotlib requests aiohttp vector pyarrow

CMD ["python", "worker.py"]