apiVersion: batch/v1
kind: Job
metadata:
  name: loader
spec:
  template:
    spec:
      containers:
      - name: loader
        image: loader-image:latest  
        imagePullPolicy: Never
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_USER
          value: user
        - name: RABBITMQ_PASSWORD
          value: password
      restartPolicy: Never
