apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: worker-image:latest
        imagePullPolicy: Never  
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_USER
          value: user
        - name: RABBITMQ_PASSWORD
          value: password
      restartPolicy: Always



