services:
  init:
    image: busybox
    volumes:
      - shared:/data
    command: sh -c "rm -rf /data/*"

  loader:
    build: ./loader
    environment:
      - OUTPUT_PATH=/data/chunks
      - PYTHONUNBUFFERED=1
    volumes:
      - shared:/data
    depends_on:
      - init

  worker:
    build: ./worker
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      replicas: 2  # Adjustable
    volumes:
      - shared:/data
    depends_on:
      - init
      - loader

  aggregator:
    build: ./outputter
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - shared:/data
    depends_on:
      - init
      - worker

volumes:
  shared:
